### ISSUE TITLE
x:typearguments

### ISSUE THREAD

**Issue by moorateeahtashil** [IncredibleWeb/Xamarin-Forms-Chat-Client#4]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Client' does not exist in the namespace 'Xamarin.Forms' (are you missing an assembly reference?)	

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'BasePage<>' does not exist in the namespace 'Client' (are you missing an assembly reference?)

**Comment by shaungrech** [comment]
The BasePage and Client are both there. Please make sure you upload your code to use the latest version of Xamarin Forms. Recently XamarinForms started using pdb files for debugging.
