### ISSUE TITLE
No License File

### ISSUE THREAD

**Issue by th174** [IncredibleWeb/Xamarin-Forms-Chat-Client#6]
How is this application licensed? This repository is missing a `LICENSE.md` file.

I noticed that some of the repo owner's other projects have an [MIT License attached](https://github.com/IncredibleWeb/MaltaJS/blob/master/LICENSE), and would like to know if this project is under the MIT License as well. 

I'm interested in using some of the code contained here for a personal project, and would like to know if that's okay with the repo owner. Of course, the source would be appropriately credited in accordance with the terms of the MIT License.

Github has an [article providing assistance](https://help.github.com/articles/adding-a-license-to-a-repository/) on adding a license to a repository.

**Comment by shaungrech** [comment]
HI I have just added a License file. Enjoy :)
